### ISSUE TITLE
Uncaught ArgumentCountError: ToolBase.php on line 118

### ISSUE THREAD

**Issue by vkulaganathan** [imgag/megSAP#230]
When trying to install megSAP [on Ubuntu22], i am getting recurrent error with executing ToolBase.php.
Any suggestions to fix this issue?

Details below:

```
$ ./download_GRCh38.sh
php $src/Tools/index_genome.php -in $genome -mask
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function ToolBase::error_handler(), 4 passed and exactly 5 expected in /home/workmegSAP/megSAP/src/Common/ToolBase.php:118
Stack trace:
#0 [internal function]: ToolBase->error_handler()
#1 /home/workmegSAP/megSAP/src/Common/functions.php(64): trigger_error()
#2 /home/workmegSAP/megSAP/src/Tools/index_genome.php(27): exec2()
#3 {main}
  thrown in /home/workmegSAP/megSAP/src/Common/ToolBase.php on line 118
```

```
$ ./download_dbs.sh

ssconvert -O 'separator="	" format=raw' -T Gnumeric_stf:stf_assistant -S hotspots_v2.xls hotspots.tsv
php $src/Tools/db_converter_cancerhotspots.php -in hotspots.tsv.0 -maf cancerhotspots.v2.maf.gz -out cancerhotspots_snv.tsv
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function ToolBase::error_handler(), 4 passed and exactly 5 expected in /home/workmegSAP/megSAP/src/Common/ToolBase.php:118
Stack trace:
#0 [internal function]: ToolBase->error_handler()
#1 /home/workmegSAP/megSAP/src/Common/functions.php(437): intdiv()
#2 /home/workmegSAP/megSAP/src/Common/ToolBase.php(82): time_readable()
#3 [internal function]: ToolBase->shutdown()
#4 {main}
  thrown in /home/workmegSAP/megSAP/src/Common/ToolBase.php on line 118
```

**Comment by marc-sturm** [comment]
You probably have PHP 8 installed:
https://stackoverflow.com/questions/65201307/too-few-arguments-to-function-exception-error-handler-php8

Only PHP 7 is supported. So please remove PHP 8 and install PHP 7.
